#!/usr/bin/env node
// Velvarr setup helper: generates a FRESH .env.local with strong secrets.
// Never overwrites an existing file and never prints secret values.

import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const target = path.join(repoRoot, ".env.local");

if (process.argv[2] === "--help") {
  console.log(
    "Usage: npm run setup [-- <origin>]   (origin optional, default http://127.0.0.1:5577)",
  );
  process.exit(0);
}

// Canonical origin: scheme + host [+ port] only. Plain HTTP is loopback-only here;
// a trusted private HTTP origin can still be configured by hand afterwards.
function canonicalOrigin(value) {
  let url;
  try {
    url = new URL(value);
  } catch {
    throw new Error(`Invalid origin: ${JSON.stringify(value)}`);
  }
  const plain = url.protocol === "http:";
  const host = url.hostname.toLowerCase();
  const loopback =
    host === "localhost" || host === "127.0.0.1" || host === "::1";
  if (
    (url.protocol !== "https:" && !plain) ||
    url.username ||
    url.password ||
    url.search ||
    url.hash ||
    (url.pathname !== "/" && url.pathname !== "")
  ) {
    throw new Error(
      "Origin must be scheme + host [+ port] only, e.g. https://velvarr.example.com",
    );
  }
  if (plain && !loopback) {
    throw new Error(
      "Plain HTTP is only accepted for loopback origins; use HTTPS, or hand-edit .env.local to add VELVARR_ALLOW_HTTP=1 for a trusted private network.",
    );
  }
  return url.origin;
}

const origin = process.argv[2]
  ? canonicalOrigin(process.argv[2])
  : canonicalOrigin("http://127.0.0.1:5577");

if (existsSync(target)) {
  console.error(`.env.local already exists at ${target}`);
  console.error(
    "Refusing to overwrite: rotating secrets would invalidate encrypted data and sessions.",
  );
  console.error(
    "Delete the file yourself only if you accept that consequence, then rerun.",
  );
  process.exit(1);
}

const secretKey = randomBytes(32).toString("hex"); // 64 hex chars = 32-byte AES-256 key
const setupSecret = randomBytes(32).toString("base64url"); // 43 chars, above the 32-char minimum

const body = [
  "# Generated by `npm run setup`. Git-ignored and excluded from the Docker context.",
  "# VELVARR_SECRET_KEY decrypts data/velvarr.sqlite; losing it loses the stored data.",
  `VELVARR_ORIGIN=${origin}`,
  `VELVARR_SECRET_KEY=${secretKey}`,
  `VELVARR_SETUP_SECRET=${setupSecret}`,
  "",
].join("\n");

try {
  writeFileSync(target, body, { flag: "wx" }); // exclusive: also fails if it appeared meanwhile
  try {
    chmodSync(target, 0o600); // best-effort owner-only perms (no-op restriction on Windows)
  } catch {
    // Windows filesystems may not support POSIX modes; file is still user-profile protected.
  }
} catch (error) {
  console.error(`Could not write ${target}: ${error.message}`);
  process.exit(1);
}

console.log(`Wrote ${target}`);
console.log(
  "Generated (values NOT printed): VELVARR_SECRET_KEY, VELVARR_SETUP_SECRET",
);
console.log(`VELVARR_ORIGIN: ${origin}`);
console.log("How it loads:");
console.log(
  "  - `npm run dev` / `npm start`: Next.js reads .env.local automatically.",
);
console.log(
  "  - Docker Compose: `docker compose up --build` (service env_file).",
);
console.log("  - Bare docker: `docker run --env-file .env.local ...`.");
console.log("  - `npm run backup` reads it for the encryption key.");
console.log(
  "Store a copy of VELVARR_SECRET_KEY in your password manager; backups are unrecoverable without it.",
);
